// <auto-generated>
//   This file contains designer-generated code for Form1.
//   Manually maintained to match the class defined in Form1.cs.
// </auto-generated>
using System;

using System.Drawing;
using System.Windows.Forms;

namespace DataUtility
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        // ── Top-level mode selector ───────────────────────────────────────────
        private GroupBox grpMode;
        private RadioButton rbComparison;
        private RadioButton rbFilter;

        // ── Data Comparison panel ─────────────────────────────────────────────
        private Panel pnlComparison;
        private GroupBox grpPrimary;
        private Label lblPrimaryFile;
        private TextBox txtPrimaryFile;
        private Button btnBrowsePrimary;
        private Label lblPrimaryHint;
       private string primaryPlaceholder = "Enter primary file path...";

        private GroupBox grpSecondary;
        private Label lblSecondaryFile;
        private TextBox txtSecondaryFile;
        private Button btnBrowseSecondary;
        private Label lblSecondaryHint;
       private string secondaryPlaceholder = "Enter secondary file path...";

        // ── Data Filter panel ─────────────────────────────────────────────────
        private Panel pnlFilter;
        private GroupBox grpFilterFile;
        private Label lblFilterFile;
        private TextBox txtFilterFile;
        private Button btnBrowseFilter;
        private Label lblFilterHint;
       private string filterPlaceholder = "Enter filter file path...";

        private GroupBox grpFilterOptions;
        private Label lblFilterDateLabel;
        private DateTimePicker dtpFilterDate;
        private RadioButton rbFilterAfter;
        private RadioButton rbFilterBefore;
        private RadioButton rbFilterExact;
        private RadioButton rbFilterBetween;
        private Label lblEndDateLabel;
        private DateTimePicker dtpEndDate;
        private Label lblMandatoryNote;

        // ── Progress section ──────────────────────────────────────────────────
        private GroupBox grpProgress;
        private ProgressBar progressBar;
        private Label lblProgressCount;
        private Label lblStatusLabel;
        private Label lblStatus;

        // ── Run button ────────────────────────────────────────────────────────
        private Button btnRun;

        // ── Title strip ───────────────────────────────────────────────────────
        private Panel pnlTitle;
        private Label lblTitle;
        private Label lblSubtitle;

        // ── Dispose ───────────────────────────────────────────────────────────
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        // ── InitializeComponent ───────────────────────────────────────────────
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();

            // ─── Form ──────────────────────────────────────────────────────────
            Text = "Data Comparison & Filter Utility";
            Size = new Size(820, 720);
            MinimumSize = new Size(820, 720);
            StartPosition = FormStartPosition.CenterScreen;
            BackColor = Color.FromArgb(30, 30, 34);
            ForeColor = Color.FromArgb(220, 220, 220);
            Font = new Font("Segoe UI", 9.5f);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            AutoScaleMode = AutoScaleMode.Font;

            // ─── Title panel ───────────────────────────────────────────────────
            pnlTitle = new Panel
            {
                Dock = DockStyle.Top,
                Height = 70,
                BackColor = Color.FromArgb(20, 20, 24),
                Padding = new Padding(16, 10, 16, 10)
            };

            lblTitle = new Label
            {
                Text = "Delta Data Utility",
                Font = new Font("Segoe UI", 16f, FontStyle.Bold),
                ForeColor = Color.FromArgb(0, 178, 255),
                AutoSize = true,
                Location = new Point(16, 10)
            };

            //lblSubtitle = new Label
            //{
            //    Text = "Compare & Filter your data files with ease",
            //    Font = new Font("Segoe UI", 9f),
            //    ForeColor = Color.FromArgb(140, 140, 160),
            //    AutoSize = true,
            //    Location = new Point(18, 42)
            //};

            pnlTitle.Controls.AddRange(new Control[] { lblTitle, lblSubtitle });

            // ─── Mode GroupBox ─────────────────────────────────────────────────
            grpMode = CreateGroupBox("Select Operation Mode", 88, 786, 70);

            rbComparison = new RadioButton
            {
                Text = "Data Comparison",
                Location = new Point(20, 30),
                Size = new Size(200, 28),
                Font = new Font("Segoe UI", 10f, FontStyle.Bold),
                ForeColor = Color.FromArgb(0, 200, 140),
                Checked = true,
                Cursor = Cursors.Hand
            };

            rbFilter = new RadioButton
            {
                Text = "Data Filter",
                Location = new Point(240, 30),
                Size = new Size(180, 28),
                Font = new Font("Segoe UI", 10f, FontStyle.Bold),
                ForeColor = Color.FromArgb(255, 160, 0),
                Cursor = Cursors.Hand
            };

            grpMode.Controls.AddRange(new Control[] { rbComparison, rbFilter });

            // ─── COMPARISON PANEL ──────────────────────────────────────────────
            pnlComparison = new Panel
            {
                Location = new Point(10, 174),
                Size = new Size(786, 220),
                Visible = true
            };

            grpPrimary = CreateGroupBox("Primary File  (drag & drop supported)", 0, 786, 100);
            lblPrimaryFile = CreateLabel("Primary File:", 16, 28);
            txtPrimaryFile = CreateFileTextBox(110, 28, 550);
           EnsurePlaceholder(txtPrimaryFile, primaryPlaceholder);
            btnBrowsePrimary = CreateBrowseButton(668, 26);
            lblPrimaryHint = CreateHintLabel("Browse or drag & drop your primary data file here.", 16, 65);
            grpPrimary.Controls.AddRange(new Control[] { lblPrimaryFile, txtPrimaryFile, btnBrowsePrimary, lblPrimaryHint });

            grpSecondary = CreateGroupBox("Secondary File  (drag & drop supported)", 110, 786, 100);
            lblSecondaryFile = CreateLabel("Secondary File:", 16, 28);
            txtSecondaryFile = CreateFileTextBox(120, 28, 540);
           EnsurePlaceholder(txtSecondaryFile, secondaryPlaceholder);
            btnBrowseSecondary = CreateBrowseButton(668, 26);
            lblSecondaryHint = CreateHintLabel("Browse or drag & drop your secondary data file here.", 16, 65);
            grpSecondary.Controls.AddRange(new Control[] { lblSecondaryFile, txtSecondaryFile, btnBrowseSecondary, lblSecondaryHint });

            pnlComparison.Controls.AddRange(new Control[] { grpPrimary, grpSecondary });

            // ─── FILTER PANEL ──────────────────────────────────────────────────
            pnlFilter = new Panel
            {
                Location = new Point(10, 174),
                Size = new Size(786, 270),
                Visible = false
            };

            grpFilterFile = CreateGroupBox("Input File  (drag & drop supported)", 0, 786, 100);
            lblFilterFile = CreateLabel("Input File:", 16, 28);
            txtFilterFile = CreateFileTextBox(90, 28, 575);
           EnsurePlaceholder(txtFilterFile, filterPlaceholder);
            btnBrowseFilter = CreateBrowseButton(668, 26);
            lblFilterHint = CreateHintLabel("Browse or drag & drop your data file to filter.", 16, 65);
            grpFilterFile.Controls.AddRange(new Control[] { lblFilterFile, txtFilterFile, btnBrowseFilter, lblFilterHint });

            grpFilterOptions = CreateGroupBox("Filter Options  (mandatory – select one)", 110, 786, 150);

            lblFilterDateLabel = CreateLabel("Filter Date:", 16, 28);
            dtpFilterDate = new DateTimePicker
            {
                Location = new Point(110, 24),
                Size = new Size(180, 26),
                Format = DateTimePickerFormat.Short,
                CalendarForeColor = Color.Black,
                BackColor = Color.FromArgb(50, 50, 58)
            };

            rbFilterAfter = CreateFilterRadio("After (≥)", 310, 26, Color.FromArgb(0, 200, 140));
            rbFilterBefore = CreateFilterRadio("Before (≤)", 410, 26, Color.FromArgb(255, 160, 0));
            rbFilterExact = CreateFilterRadio("Exact (=)", 510, 26, Color.FromArgb(0, 178, 255));
            rbFilterBetween = CreateFilterRadio("Between", 610, 26, Color.FromArgb(200, 80, 200));
            rbFilterAfter.Checked = true;

            lblEndDateLabel = CreateLabel("End Date:", 16, 68);
            lblEndDateLabel.ForeColor = Color.FromArgb(140, 140, 160);
            dtpEndDate = new DateTimePicker
            {
                Location = new Point(110, 64),
                Size = new Size(180, 26),
                Format = DateTimePickerFormat.Short,
                Enabled = false
            };

            rbFilterBetween.CheckedChanged += (s, e) =>
            {
                dtpEndDate.Enabled = rbFilterBetween.Checked;
                lblEndDateLabel.ForeColor = rbFilterBetween.Checked
                    ? Color.FromArgb(220, 220, 220)
                    : Color.FromArgb(140, 140, 160);
            };

            lblMandatoryNote = new Label
            {
                Text = "⚠  Configuration.xml drives column names, date formats, and output settings.",
                Location = new Point(16, 110),
                Size = new Size(750, 22),
                ForeColor = Color.FromArgb(255, 200, 60),
                Font = new Font("Segoe UI", 8.5f, FontStyle.Italic)
            };

            grpFilterOptions.Controls.AddRange(new Control[]
            {
                lblFilterDateLabel, dtpFilterDate,
                rbFilterAfter, rbFilterBefore, rbFilterExact, rbFilterBetween,
                lblEndDateLabel, dtpEndDate, lblMandatoryNote
            });

            pnlFilter.Controls.AddRange(new Control[] { grpFilterFile, grpFilterOptions });

            // ─── Progress GroupBox ─────────────────────────────────────────────
            grpProgress = CreateGroupBox("Execution Progress", 455, 786, 110);

            progressBar = new ProgressBar
            {
                Location = new Point(16, 30),
                Size = new Size(640, 28),
                Minimum = 0,
                Maximum = 100,
                Style = ProgressBarStyle.Continuous,
                ForeColor = Color.FromArgb(0, 178, 255)
            };

            lblProgressCount = new Label
            {
                Text = "0%",
                Location = new Point(666, 33),
                Size = new Size(100, 22),
                ForeColor = Color.FromArgb(0, 200, 140),
                Font = new Font("Segoe UI", 9f, FontStyle.Bold)
            };

            lblStatusLabel = CreateLabel("Status:", 16, 68);
            lblStatusLabel.ForeColor = Color.FromArgb(140, 140, 160);
            lblStatus = new Label
            {
                Text = "Ready.",
                Location = new Point(70, 65),
                Size = new Size(700, 22),
                ForeColor = Color.FromArgb(200, 200, 200),
                Font = new Font("Segoe UI", 9f)
            };

            grpProgress.Controls.AddRange(new Control[]
            {
                progressBar, lblProgressCount, lblStatusLabel, lblStatus
            });

            // ─── Run button ────────────────────────────────────────────────────
            btnRun = new Button
            {
                Text = "▶   Run",
                Location = new Point(10, 580),
                Size = new Size(786, 48),
                Font = new Font("Segoe UI", 12f, FontStyle.Bold),
                ForeColor = Color.White,
                BackColor = Color.FromArgb(0, 122, 204),
                FlatStyle = FlatStyle.Flat,
                Cursor = Cursors.Hand
            };
            btnRun.FlatAppearance.BorderSize = 0;
            btnRun.FlatAppearance.MouseOverBackColor = Color.FromArgb(0, 100, 180);

            // ─── Add all to form ───────────────────────────────────────────────
            Controls.AddRange(new Control[]
            {
                pnlTitle,
                grpMode,
                pnlComparison,
                pnlFilter,
                grpProgress,
                btnRun
            });
        }

        // ── Factory helpers ───────────────────────────────────────────────────

        private GroupBox CreateGroupBox(string title, int top, int width, int height)
        {
            return new GroupBox
            {
                Text = title,
                Location = new Point(10, top),
                Size = new Size(width, height),
                ForeColor = Color.FromArgb(160, 160, 180),
                Font = new Font("Segoe UI", 9f, FontStyle.Regular),
                BackColor = Color.FromArgb(38, 38, 44),
                Padding = new Padding(6)
            };
        }

        private Label CreateLabel(string text, int x, int y)
        {
            return new Label
            {
                Text = text,
                Location = new Point(x, y + 3),
                AutoSize = true,
                ForeColor = Color.FromArgb(180, 180, 200)
            };
        }

        private Label CreateHintLabel(string text, int x, int y)
        {
            return new Label
            {
                Text = text,
                Location = new Point(x, y),
                Size = new Size(740, 22),
                ForeColor = Color.FromArgb(100, 100, 120),
                Font = new Font("Segoe UI", 8f, FontStyle.Italic)
            };
        }

        private TextBox CreateFileTextBox(int x, int y, int width)
        {
            return new TextBox
            {
                Location = new Point(x, y),
                Size = new Size(width, 26),
                BackColor = Color.FromArgb(50, 50, 58),
                ForeColor = Color.FromArgb(220, 220, 220),
                BorderStyle = BorderStyle.FixedSingle,
                ReadOnly = false
            };
        }

        private Button CreateBrowseButton(int x, int y)
        {
            var btn = new Button
            {
                Text = "Browse …",
                Location = new Point(x, y - 1),
                Size = new Size(100, 28),
                BackColor = Color.FromArgb(55, 55, 65),
                ForeColor = Color.FromArgb(200, 200, 220),
                FlatStyle = FlatStyle.Flat,
                Cursor = Cursors.Hand
            };
            btn.FlatAppearance.BorderColor = Color.FromArgb(80, 80, 100);
            return btn;
        }

        private RadioButton CreateFilterRadio(string text, int x, int y, Color color)
        {
            return new RadioButton
            {
                Text = text,
                Location = new Point(x, y + 2),
                AutoSize = true,
                ForeColor = color,
                Font = new Font("Segoe UI", 9f),
                Cursor = Cursors.Hand
            };
        }
    }
}
